apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: mini-project3
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::805400277714:role/team01-mini-project3-eso-sa-role