apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mini-project3
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # [1] 테라폼에서 설정한 frontend 노드 그룹에만 파드가 배치되도록 설정
      nodeSelector:
        role: frontend
      containers:
      - name: frontend-container
        image: 805400277714.dkr.ecr.ap-northeast-2.amazonaws.com/team01-mini-project3/frontend:d93e29d37a73a8ef70adf81e8c17a103d261acd5
        ports:
        - containerPort: 80