apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mini-project3  
spec:
  type: NodePort             # ALB Ingress가 인식할 수 있도록 NodePort 사용
  selector:
    app: backend             # backend-deployment.yaml의 label과 일치해야 함
  ports:
    - port: 80             # 서비스가 노출할 포트
      targetPort: 8080       # 실제 컨테이너의 포트
      protocol: TCP