apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mini-project3
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # [1] 테라폼에서 설정한 backend 노드 그룹에만 파드가 배치되도록 설정
      nodeSelector:
        role: backend
      containers:
      - name: backend-container
        image: 805400277714.dkr.ecr.ap-northeast-2.amazonaws.com/team01-mini-project3/backend:006be8fabbf91d0cff621e66a9fc157591ce274c
        ports:
        - containerPort: 8080 # Spring Boot 기본 포트
        env:
        - name: DB_HOST
          value: "terraform-20260508075842560200000001.c18y4gs8uo61.ap-northeast-2.rds.amazonaws.com"
        - name: REDIS_HOST
          value: "지수님의- 실제-redis-엔드포인트-주소" # 실제 주소로 교체 필요
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"