apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mini-project3
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    #alb.ingress.kubernetes.io/success-codes: '200,302,403,405'
spec:                  # 이 줄 추가
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP