apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mini-project3
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # [1] 테라폼에서 설정한 backend 노드 그룹에만 파드가 배치되도록 설정
      nodeSelector:
        role: backend
      containers:
      - name: backend-container
        image: 805400277714.dkr.ecr.ap-northeast-2.amazonaws.com/team01-mini-project3/backend:c3c82643f3de2f85ebde4b547fa829153814821b
        ports:
        - containerPort: 8080 # Spring Boot 기본 포트
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secret    # ExternalSecret이 생성한 K8s Secret
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: REDIS_HOST
        - name: TZ
          value: Asia/Seoul  # 타임존을 서울로 설정
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"